version: '3.3'
services:
  server:
    build: server
    ports:
      - 8081:8081
  client:
    build: client
    ports:
      - 8080:80
    volumes:
      - /data/certs:/etc/nginx/certs
    depends_on:
      - server
